import { Text } from "components/Text";
export const globalInstructions = (
  <Text>
    Was hätten Sie an seiner / ihrer Stelle gemacht?
    <br />
    Was würden Sie an seiner / ihrer Stelle tun?
  </Text>
);
export const sentences = [
  {
    instructions: "Sie hat wenig Sport getrieben",
    answers: ["An ihrer Stelle hätte ich mehr Sport getrieben"],
    options: [
      "an",
      "ihrer",
      "seiner",
      "Stelle",
      "hätte",
      "würde",
      "ich",
      "mehr",
      "Sport",
      "getrieben",
    ],
  },
  {
    instructions: "Er rauch in jeder Pause",
    answers: ["An seiner Stelle würde ich nicht so viel rauchen"],
    options: [
      "an",
      "ihrer",
      "seiner",
      "Stelle",
      "hätte",
      "würde",
      "ich",
      "nicht",
      "so",
      "viel",
      "rauchen",
    ],
  },
  {
    instructions: "Er hat die letzten Tage viel gearbeitet",
    answers: [
      "An seiner Stelle hätte ich die letzten Tage nich so viel gearbeitet",
    ],
    options: [
      "an",
      "seiner",
      "ihrer",
      "Stelle",
      "hätte",
      "wäre",
      "ich",
      "die letzten",
      "der letzte",
      "Tage",
      "nich so viel",
      "gearbeitet",
      "arbeiten",
    ],
  },
  {
    instructions: "Er trinkt morgens viel Kaffee",
    answers: [
      "An seiner Stelle würde ich morgens nicht so viel Kaffee trinken",
    ],
    options: [
      "an",
      "ihrer",
      "seiner",
      "Stelle",
      "würde",
      "hätte",
      "ich",
      "morgens",
      "Morgens",
      "nicht",
      "so viel",
      "zu viel",
      "Kaffee",
      "trinken",
      "getrunken",
    ],
  },
  {
    instructions: "Trotz Krankheit blieb sie nicht zu Hause",
    answers: ["An ihrer Stelle wäre ich zu Hause geblieben"],
    options: [
      "an",
      "seiner",
      "ihrer",
      "Stelle",
      "wäre",
      "hätte",
      "würde",
      "ich",
      "zu Hause",
      "geblieben",
      "bleiben",
    ],
  },
  {
    instructions: "Sie nahm ihren Urlaub nicht",
    answers: ["An ihrer Stelle hätte ich meinen Urlaub genommen"],
    options: [
      "an",
      "seiner",
      "ihrer",
      "Stelle",
      "hätte",
      "würde",
      "ich",
      "meinen",
      "meinem",
      "Urlaub",
      "genommen",
      "nehmen",
    ],
  },
  {
    instructions: "Er kommt heute nicht ins Büro",
    answers: ["An seiner Stelle würde ich heute ins Büro kommen"],
    options: [
      "an",
      "seiner",
      "ihrer",
      "Stelle",
      "würde",
      "wäre",
      "ich",
      "heute",
      "ins",
      "im",
      "Büro",
      "kommen",
      "gekommen",
    ],
  },
  {
    instructions: "Sie hat das Angebot abgelehnt",
    answers: [
      "An ihrer Stelle hätte ich das Angebot angenommen",
      "An ihrer Stelle hätte ich das Angebot nicht abgelehnt",
    ],
    options: [
      "an",
      "seine",
      "ihrer",
      "Stelle",
      "hätte",
      "wäre",
      "ich",
      "das",
      "dem",
      "Angebot",
      "angenommen",
      "nicht",
      "abgelehnt",
      "nehmen",
    ],
  },
];
