export const globalInstructions =
  "Formulieren Sie die Sätze mit als ob und mit als. ";
export const sentences = [
  {
    instructions: "Meine Kollegin / immer so tun / sie alles wissen (als ob)",
    answers: ["Meine Kollegin tut immer so, als ob sie alles wüsste"],
    options: [
      "meine Kollegin",
      "tut",
      "tun",
      "immer so,",
      "als ob",
      "sie",
      "alles",
      "wüsste",
      "würde",
      "wissen",
    ],
  },
  {
    instructions: "sie / sich so verhalten - die Chefin sein (als)",
    answers: ["Sie verhält sich, als wäre sie die Chefin"],
    options: [
      "sie",
      "verhält",
      "verhalten",
      "sich,",
      "als",
      "wäre",
      "sein",
      "sie",
      "die Chefin",
    ],
  },
  {
    instructions:
      "sie / oft ohne Entschuldigung zu spät kommen - das Recht dazu haben (als ob)",
    answers: [
      "Sie kommt oft ohne Entschuldigung zu spät, als ob sie das Recht dazu hätte",
    ],
    options: [
      "sie",
      "kommt",
      "kommen",
      "oft",
      "ohne Entschuldigung",
      "zu spät,",
      "als ob",
      "sie",
      "das Recht",
      "dazu",
      "hätte",
      "haben",
      "würde",
    ],
  },
  {
    instructions: "sie / sich oft Benehmen - im Büro zu Hause sein (als ob)",
    answers: ["Sie benimmt sich oft so, als ob sie im Büro zu Hause wäre"],
    options: [
      "sie",
      "benimmt",
      "benehmen",
      "sich",
      "oft so,",
      "als ob",
      "sie",
      "im Büro",
      "ins Büro",
      "zu Hause",
      "wäre",
      "sein",
      "würde",
    ],
  },
  {
    instructions:
      "sie / so oft tun - dir Kritik nicht verstehen können (als ob)",
    answers: ["Sie tut oft so, als ob sie die Kritik nicht verstehen könnte"],
    options: [
      "sie",
      "tut",
      "oft so,",
      "als ob",
      "sie",
      "die Kritik",
      "der Kritik",
      "nicht verstehen",
      "könnte",
      "kann",
      "würden",
    ],
  },
  {
    instructions:
      "sie / für die Betriebsfeier so viel zu essen besorgt - eine Fußballmanschaft kommt zu Gast (als)",
    answers: [
      "Sie besorgt für die Betriebsfeier so viel zu essen, als käme eine Fußballmannschaft zu Gast",
    ],
    options: [
      "sie",
      "besorgt",
      "für",
      "die",
      "Betriebsfeier",
      "der",
      "so viel",
      "zu",
      "essen,",
      "als",
      "käme",
      "wäre",
      "kommen",
      "eine Fußballmannschaft",
      "zu Gast",
    ],
  },
];
